/**
 * notifications.ts — Local notification service for SentinelEdge mobile.
 *
 * All notifications are LOCAL — generated by the app from WebSocket data.
 * No Expo push server, no Expo account, no EAS needed.
 */

import * as Notifications from 'expo-notifications';
import { Audio } from 'expo-av';
import { Platform } from 'react-native';

// Configure how notifications are presented when app is foregrounded
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
  }),
});

let _soundObject: Audio.Sound | null = null;

export async function requestNotificationPermissions(): Promise<boolean> {
  const { status: existing } = await Notifications.getPermissionsAsync();
  if (existing === 'granted') return true;
  const { status } = await Notifications.requestPermissionsAsync();
  return status === 'granted';
}

export async function scheduleLocalNotification(
  title: string,
  body: string
): Promise<void> {
  try {
    const granted = await requestNotificationPermissions();
    if (!granted) return;

    await Notifications.scheduleNotificationAsync({
      content: {
        title,
        body,
        sound: true,
        priority: Notifications.AndroidNotificationPriority.MAX,
        vibrate: [0, 250, 250, 250],
      },
      trigger: null, // fire immediately
    });
  } catch (err) {
    console.warn('[Notifications] scheduleLocalNotification failed:', err);
  }
}

export async function playAlarmSound(level: 1 | 2 | 3 = 1): Promise<void> {
  try {
    await Audio.setAudioModeAsync({
      playsInSilentModeIOS: true,
      staysActiveInBackground: false,
    });

    // Stop any currently playing sound
    if (_soundObject) {
      await _soundObject.stopAsync().catch(() => {});
      await _soundObject.unloadAsync().catch(() => {});
      _soundObject = null;
    }

    // Try to load beep.mp3 from assets/. If absent, fall back to vibration only.
    // To add sound: place a short beep.mp3 in frontend-mobile/assets/beep.mp3
    try {
      const { sound } = await Audio.Sound.createAsync(
        require('../../assets/beep.mp3'),
        { shouldPlay: true, isLooping: level === 3, volume: 0.8 }
      );
      _soundObject = sound;

      if (level !== 3) {
        const duration = level === 1 ? 600 : 900;
        setTimeout(() => stopAlarmSound(), duration);
      }
    } catch (_assetErr) {
      // beep.mp3 not present — the notification sound from the OS will play instead
      console.info('[Notifications] beep.mp3 not found; using system notification sound.');
    }
  } catch (err) {
    console.warn('[Notifications] playAlarmSound failed:', err);
  }
}

export async function stopAlarmSound(): Promise<void> {
  try {
    if (_soundObject) {
      await _soundObject.stopAsync();
      await _soundObject.unloadAsync();
      _soundObject = null;
    }
  } catch (err) {
    console.warn('[Notifications] stopAlarmSound failed:', err);
  }
}
